require: rubocop-rails
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/Documentation:
  Enabled: false
Rails:
  Enabled: true
Rails/FilePath:
  Exclude:
    - config/environments/development.rb
Rails/HasManyOrHasOneDependent:
  Exclude:
    - app/models/user.rb
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 18
Naming/MemoizedInstanceVariableName:
  Enabled: false
Style/GuardClause:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
    