default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  timeout: 5000

development:
  <<: *default
  database: web_app_development

test:
  <<: *default
  database: web_app_test

production:
  <<: *default
  database: web_app_production
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
